### ISSUE TITLE
Possible non-standard definition of 'percentile' in use?

### ISSUE THREAD

**Issue by TSSlade** [ftc-scout/ftc-scout#2]
It looks like the values currently displayed aren't the standard definition of percentile (where a score in the 99th pctile means 99 pct of scores are _at or below_ that value) (ref: [Wikipedia](https://en.wikipedia.org/wiki/Percentile?wprov=sfla1)) but rather may instead be "the proportion of scores greater than this score".

It seems improbable, for instance, that roughly 0% of scores fall BELOW the scores of Cybugs, the top-ranked team in the world per FTCScout's rankings:
![Screenshot_20231216_184845_Brave.jpg](https://github.com/ftc-scout/ftc-scout/assets/3211478/184b03d6-c68f-4d20-89da-2fd4aaa3518f)

**Comment by Dragon-Hatcher** [comment]
You’re absolutely right; this is the opposite of a percentile. I could reverse it or if there is a different word we could use?

**Comment by 9021007** [comment]
You could do "top X%" or just reverse it
