### ISSUE TITLE
Rest route for accessing every team's quickstats

### ISSUE THREAD

**Issue by KennanHunter** [ftc-scout/ftc-scout#5]
With FTCStats down we're looking at using your opr data to help determine global opr rankings, but any request to view global stats times out.

As it is you can only access quickstats by performing a lookup on the specific Team, meaning seeing every team's opr in a ranking slows to a crawled. This could be solved by having a `teams/ranking` api route or something along that line that performs the join at database level. I can't think of any way to get this to work cleanly with graphql. I could probably implement myself if needed.

**Comment by 9021007** [comment]
Here is a GraphQL Query:

```
{
  tepRecords(season:2024, skip:0, take:100, region:All, ) {
    data {
      noFilterRank
      data {
        teamNumber
      }
    }
  }
}
```

**Comment by KennanHunter** [comment]
Thanks! This should do what we need.
